### ISSUE TITLE
Directory resource: not possible to resume

### ISSUE THREAD

**Issue by cryptotester** [ipfs/ipget#96]
- Try to download a resource directory
- Wait for some progress, so that inside the local directory some files have been downloaded
- Press Ctrl-C to stop
- Run the command again

Result: ipget tells that it can't overwrite existing local files

Expected result: it should resume and download what's new, files not fully downloaded should either resume or being re-downloaded.

**Comment by Stebalien** [comment]
If you have a full IPFS node installed, `ipget` will use it and the chunks will still be available in your main repo (so you can resume).

Otherwise, this is technically possible but difficult as there are different ways to "chunk" files, resulting in different CIDs. You'd need to:

1. Re-start the download, re-downloading the _indirect_ (not data) blocks.
2. Before downloading a block, use the offset/size (usually included in the indirect blocks) to check to see if that chunk of the file matches.

However, this would require some new traversal logic. I'd suggest implementing a feature like this in a fork although I can't guarantee that someone will be able to review your code in the near future.

**Comment by cryptotester** [comment]
Thanks for the answer. I could already sort my issue using not a full node, but IPFS Desktop + a script in python to download from localhost:8080 (ipfs desktop) so I assume this could work also using IPFS Desktop from what you know?

**Comment by guseggert** [comment]
This is difficult enough that we're not going to prioritize it.

**Comment by stdedos** [comment]
_Closed as incomplete?_
